/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.pim.view;

/**
 *
 * @author JOSUE
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        itmNew = new javax.swing.JMenuItem();
        itmOpen = new javax.swing.JMenuItem();
        itmSave = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenu();
        itmNewUser = new javax.swing.JMenuItem();
        itmModifyUser = new javax.swing.JMenuItem();
        itmDeleteUser = new javax.swing.JMenuItem();
        mnInventory = new javax.swing.JMenu();
        itmAddShoe = new javax.swing.JMenuItem();
        itmModifyShoe = new javax.swing.JMenuItem();
        itmDeleteShoe = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        itmComentary = new javax.swing.JMenuItem();
        itmAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Inventory Manager");

        mnFile.setText("File");

        itmNew.setText("New");
        itmNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmNewActionPerformed(evt);
            }
        });
        mnFile.add(itmNew);

        itmOpen.setText("Open");
        mnFile.add(itmOpen);

        itmSave.setText("Save");
        mnFile.add(itmSave);

        itmExit.setText("Exit");
        itmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitActionPerformed(evt);
            }
        });
        mnFile.add(itmExit);

        jMenuBar1.add(mnFile);

        mnUser.setText("User");

        itmNewUser.setText("Add New User");
        mnUser.add(itmNewUser);

        itmModifyUser.setText("Modify User");
        itmModifyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmModifyUserActionPerformed(evt);
            }
        });
        mnUser.add(itmModifyUser);

        itmDeleteUser.setText("Delete User");
        mnUser.add(itmDeleteUser);

        jMenuBar1.add(mnUser);

        mnInventory.setText("Inventory");

        itmAddShoe.setText("Add Shoe");
        mnInventory.add(itmAddShoe);

        itmModifyShoe.setText("Modify Shoe");
        mnInventory.add(itmModifyShoe);

        itmDeleteShoe.setText("Delete Shoe");
        mnInventory.add(itmDeleteShoe);

        jMenuBar1.add(mnInventory);

        mnHelp.setText("Help");

        itmComentary.setText("Send Comentary");
        itmComentary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmComentaryActionPerformed(evt);
            }
        });
        mnHelp.add(itmComentary);

        itmAbout.setText("About PIM");
        itmAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAboutActionPerformed(evt);
            }
        });
        mnHelp.add(itmAbout);

        jMenuBar1.add(mnHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmModifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmModifyUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmModifyUserActionPerformed

    private void itmNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmNewActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new frmSignIn().setVisible(true);
    }//GEN-LAST:event_itmNewActionPerformed

    private void itmComentaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmComentaryActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new frmComentary().setVisible(true);
    }//GEN-LAST:event_itmComentaryActionPerformed

    private void itmAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAboutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new frmAbout().setVisible(true);
    }//GEN-LAST:event_itmAboutActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itmExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAbout;
    private javax.swing.JMenuItem itmAddShoe;
    private javax.swing.JMenuItem itmComentary;
    private javax.swing.JMenuItem itmDeleteShoe;
    private javax.swing.JMenuItem itmDeleteUser;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmModifyShoe;
    private javax.swing.JMenuItem itmModifyUser;
    private javax.swing.JMenuItem itmNew;
    private javax.swing.JMenuItem itmNewUser;
    private javax.swing.JMenuItem itmOpen;
    private javax.swing.JMenuItem itmSave;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenu mnInventory;
    private javax.swing.JMenu mnUser;
    // End of variables declaration//GEN-END:variables
}
